name: Microservicio Estudiante CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Configurar Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d

      - name: Esperar a que MongoDB esté listo
        run: |
          for i in {1..10}; do
            nc -z localhost 27017 && echo "MongoDB está listo" && exit 0
            echo "Esperando MongoDB..."
            sleep 3
          done
          echo "MongoDB no se inició a tiempo" && exit 1

      - name: Verificar que el servicio estudiante esté corriendo
        run: |
          curl --fail http://localhost:5000 || (echo "El servicio estudiante no respondió" && exit 1)

      - name: Apagar servicios
        if: always()
        run: docker-compose -f docker-compose.yml down
